### ISSUE TITLE
Symbol not found: _objc_opt_new

### ISSUE THREAD

**Issue by ihbing** [ptoomey3/Keychain-Dumper#55] opened 2020-07-01 02:47 UTC
```
#cd /private/var/Keychains/
#chmod 777 /bin/keychain_dumper
#/bin/keychain_dumper > keychain-export.txt
```

dyld: Symbol not found: _objc_opt_new
  Referenced from: /bin/keychain_dumper (which was built for iOS 13.5)
  Expected in: /usr/lib/libobjc.A.dylib
 in /bin/keychain_dumper
Abort trap: 6

The device info :
iOS 12.4
iPhone6

**Comment by mayankraheja98** [comment] 2020-07-01 12:24
facing same issue
iphone 5s
ios 12.4.6

**Comment by movses-margaryan** [comment] 2020-07-09 06:40
xcode-select to Xcode 10.3 command line tools worked for me

**Comment by Zatyam** [comment] 2020-08-24 18:33
Facing the same issue on iPhone 6, iOS 12.4.4
I don't have a Mac to run the above xcode-select command on Xcode. Please help

**Comment by ptoomey3** [comment] 2020-09-08 14:14
Closing as a duplicate of https://github.com/ptoomey3/Keychain-Dumper/issues/53. I'm going to try and see if building under Xcode 10.3 fixes the issue.

**Closed by ptoomey3** 2020-09-08 14:14 UTC
