### ISSUE TITLE
Segmentation Fault: 11

### ISSUE THREAD

**Issue by jairoserranosp** [ptoomey3/Keychain-Dumper#28] opened 2017-02-07 17:49 UTC
root# ./keychain_dumper -a > keychain_dump.log
Segmentation fault: 11

iPhone 8,1 iOS 9.1 Cydia64_1.1.28

**Comment by ptoomey3** [comment] 2017-02-07 17:54
My apologies, I haven't kept current with jailbreaking and have no way to test/fix anything. If someone can reproduce/fix it, I'd be open to reviewing/merging a PR.

**Comment by cyru5xl** [comment] 2017-06-19 16:28
Same issue happening for me ipad air2  iOs 8.4  - cydia 1.1.23
root# ./keychain_dumper -k > dump.log
Only has issue dumping the keys : Segmentation fault: 11
Anything I need to do to fix? Perhaps a x64 issue?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment] 2017-07-25 09:15
Hi!
Same issue here, on `iPhone 8,1, iOS 10.1 Cydia64_1.1.30`
Only segfault when dumping key  (with `-k` or `-a`)
```
iPhone-XXXXXXX:~ root# ./keychain_dumper -k

[...]

Key
---
Entitlement Group: com.apple.CoreSuggestions
Label: (null)
Keychain protection class: kSecAttrAccessibleWhenUnlocked
Application Label: <53475361 6c74>
Key Class: Public
Segmentation fault: 11
iPhone-XXXXXXX:~ root# 
```

**Comment by notoriousturtle** [comment] 2018-01-31 03:18
Looks like the empty key bug.

**Comment by ikkisoft** [comment] 2018-03-24 18:30
Agree. Try merging this PR locally https://github.com/ptoomey3/Keychain-Dumper/pull/12

**Comment by rkim-ias** [comment] 2019-03-07 22:42
I wonder if this has to do with how all 64 bit devices have the Secure Enclave for managing certain keys. (Secure Enclave is available from Apple A7[or iPhone 5s, iPad Mini 2] and up). It may explain the empty key bug.

**Comment by ptoomey3** [comment] 2019-03-11 13:09
Does #12 resolve the issue? I've fallen out of the jailbreak world, so don't have easy access to a device to test on. But, I can try and get #12 merged if folks think it worthwhile.

**Comment by ptoomey3** [comment] 2020-09-08 14:09
Closing as stale.

**Closed by ptoomey3** 2020-09-08 14:09 UTC
